force-app/main/default/objects/Key_Metrics_Setting__mdt/Key_Metrics_Setting__mdt.object-meta.xml
<CustomObject>
    <description>Settings for configuring the Key Metrics LWC. The LWC sits on a Lightning Record Page and displays up to four key metrics in nicely displayed cards with dynamic rendering. As records are updated, metrics cards are updated in real time.</description>
    <label>Key Metrics Setting</label>
    <pluralLabel>Key Metrics Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Key_Metrics_Setting__mdt/fields/Card_Format__c.field-meta.xml
<CustomField>
    <fullName>Card_Format__c</fullName>
    <description>Displays cards across the layout either in a 1, 2, 3, or 4-up configuration.</description>
    <inlineHelpText>It is recommended for smaller devices to use the 1-up or 2-Up configuration</inlineHelpText>
    <label>Card Format</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>1-Up</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>2-Up</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>3-Up</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>4-Up</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Key_Metrics_Setting__mdt/fields/Currency_Format__c.field-meta.xml
<CustomField>
    <fullName>Currency_Format__c</fullName>
    <description>Used to configure the currency-display-as of the formatted number base component for currency metrics</description>
    <inlineHelpText>Will render as follows: symbol: $, Code: USD, Name: US dollars</inlineHelpText>
    <label>Currency Format</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>symbol</fullName>
                <default>true</default>
                <label>symbol</label>
            </value>
            <value>
                <fullName>code</fullName>
            </value>
            <value>
                <fullName>name</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Key_Metrics_Setting__mdt/fields/Metric_1_Label__c.field-meta.xml
<CustomField>
    <fullName>Metric_1_Label__c</fullName>
    <description>Label of the metric as you&apos;d like it displayed in the LWC</description>
    <label>Metric 1 Label</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Key_Metrics_Setting__mdt/fields/Metric_4_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Metric_4_API_Name__c</fullName>
    <description>API Name of the field on the object for metric 2</description>
    <label>Metric 4 API Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/KeyMetricsControllerTest.cls
/**
 * @author John Scardino
 * @date 2024
 * 
 * @description Test class for KeyMetricsController to ensure metric configuration are returned as expected.
 * Uses the SeeAllData=true flag to test the included example Custom Metadata Type record.
 */
@isTest(SeeAllData=true)
private class KeyMetricsControllerTest {

@isTest
    static void testGetMetadataValues() {
        
        // Create test user with System Administrator profile
        Profile adminProfile = [SELECT Id FROM Profile WHERE Name = 'System Administrator' WITH USER_MODE LIMIT 1];
        User testUser = new User(
            Alias = 'testU',
            Email = 'example@none.com',
            EmailEncodingKey = 'UTF-8',
            LastName = 'MetricsTester',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ProfileId = adminProfile.Id,
            TimeZoneSidKey = 'America/Los_Angeles',
            UserName = 'example321@none.com'
        );
        insert testUser;
        
        System.runAs(testUser) {
            // Test the getMetadataValues method
            Test.startTest();
            Key_Metrics_Setting__mdt setting = KeyMetricsController.getMetadataValues('Example Settings');
            Test.stopTest();
            
            // Assert a representative number of the results
            System.assertEquals('3', setting.Card_Format__c, 'Card format value is incorrect or missing.');
            System.assertEquals('Annual Revenue', setting.Metric_1_Label__c, 'Metric 1 label is incorrect or missing.');
            System.assertEquals('symbol', setting.Currency_Format__c, 'Currency Format is incorrect or missing.');
            System.assertEquals(null, setting.Metric_4_API_Name__c, 'Metric 4 API Name should be null.');
        }
    }
}